language: python
python:
- "3.6"
services:
  - docker
script:
  - npm install -g serverless
  - npm install serverless-python-requirements
  - pip install pipenv
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then sls deploy -v --force --conceal; fi'
branches:
  only:
    - master
