service: hyperbudget-email-service # NOTE: update this with your service name

plugins:
  - serverless-python-requirements

provider:
  name: aws
  runtime: python3.6
  region: eu-west-2
  stage: ${opt:stage, 'dev'}
  environment:
    SQS_QUEUE: ${self:service}-${self:provider.stage}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - "sqs:SendMessage"
        - "sqs:GetQueueUrl"
      Resource: "arn:aws:sqs:${opt:region, self:provider.region}:*:${self:provider.environment.SQS_QUEUE}"
    - Effect: Allow
      Action:
        - "sqs:ListQueues"
      Resource: "arn:aws:sqs:${opt:region, self:provider.region}:*:*"
    - Effect: Allow
      Action:
        - "ses:SendEmail"
      Resource: "arn:aws:ses:eu-west-1:*:*"

functions:
  sendEmail:
    handler: service.handler.send_email

    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - sqsQueue
              - Arn

resources:
  Resources:
    sqsQueue:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: "${self:provider.environment.SQS_QUEUE}"

custom:
  pythonRequirements:
    dockerizePip: true
